<?php

namespace app\admin\controller;

use think\Controller;

class Book extends Controller
{
    //初始化登录页面，在没有登录的情况下直接跳转到登录页面
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session('?email')) {
            $this->redirect('admin/User/login');
        }

    }

    //后台首页
    public function template()
    {
        return view();
    }

    //图书展示页面
    public function booklist()
    {
        // 查询状态为1的用户数据 并且每页显示10条数据
        $list = model('book')->paginate(10);
        // 把分页数据赋值给模板变量list
        $this->assign('list', $list);
        return view();
    }

    //图书添加页面
    public function bookadd()
    {
        //接受Ajax值
        if (request()->isAjax()) {
            //接受数据
            $data = [
                'isbn' => input('isbn'),
                'name' => input('name'),
                'price' => input('price'),
                'num' => input('num'),
                'picture' => input('picture'),
            ];
            //模型验证
            $res = model('Book')->bookadd($data);
            if ($res == 1) {
                $this->success('添加成功', 'admin/Book/booklist');
            } else {
                $this->error($res);
            }

        }
        return view();
    }

    //图书详情页展示
    public function details()
    {
        //isbn号
        $data = [
            'isbn' => input('isbn'),
        ];
        $res = model('book')->where('isbn', $data['isbn'])->find();

        $this->assign('res', $res);
        return view();
    }

    //删除
    public function bookdelete()
    {
        if (request()->isAjax()) {
            $data = request()->put();
            $res = model('book')->where('isbn', $data['isbn'])->delete();
            if ($res) {
                $this->success('删除成功', 'admin/Book/booklist');
            }
        }
    }

    //编辑页面
    public function bookedit()
    {

        if (request()->isAjax()) {
            //接受数据
            $data = request()->put();
//            $data = [
//                'isbn' => input('isbn'),
//                'name' => input('name'),
//                'price' => input('price'),
//                'num' => input('num'),
//                'picture' => input('picture'),
//            ];
            $res = model('Book')->bookedit($data);
            if ($res == 1) {
                $this->success('编辑成功', 'admin/Book/booklist');
            } else {
                $this->error($res);
            }
        }

        //给bookedit页面传输数据
        $data = [
            'isbn' => input('isbn'),
        ];
        $res = model('book')->where('isbn', $data['isbn'])->find();
        $this->assign('res', $res);

        return view();

    }

}
